name: CI

on:
  schedule:
    - cron: '30 3 * * *'  
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Make the script executable
        run: chmod +x hello_world.sh

      - name: Run the hello world script
        run: ./hello_world.sh

      - name: cat new_file.txt
        run: cat new_file.txt

      - name: cat new_file2.txt
        run: cat new_file2.txt


    














